.TH "KEUROCALC" "1" 
.SH "NAME" 
keurocalc \(em A KDE-based universal currency converter and calculator. 
.SH "SYNOPSIS" 
.PP 
\fBkeurocalc\fR [\fB\-\-help\fI\fR\fP]  [\fB\-\-help-kde\fI\fR\fP]  [\fB\-\-help-qt\fI\fR\fP]  [\fB\-\-version\fI \-v\fR\fP]  [\fB\-\-license\fI\fR\fP]  [\fB\-\-author\fI\fR\fP]    
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBkeurocalc\fR command. 
.PP 
\fBkeurocalc\fR is a KDE-based universal currency converter and calculator. 
It downloads latest exchange rates directly from the
European Central Bank and the Federal Reserve Bank of New York.

.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. However, the ordering is very strict \- 
\-\-help/\-h must come before hostname. 
.IP "\fB-v\fP 	  \fB\-\-version\fP 	" 10 
Show version information. 
.IP "\fB\-\-author\fP 	" 10 
Show information about the author. 
.IP "\fB\-\-license\fP 	" 10 
Show license information. 
.IP "\fB\-\-caption <caption>\fP 	" 10 
.SH "AUTHOR" 
.PP 
This manual page was written by Claudio Moratti <maxer@knio.it> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  
Permission is granted to copy, distribute and/or modify this document 
under the terms of the GNU Public License, Version 2  
or any later version published by the Free Software Foundation.
